version: "3.7"
services:
  traefik:
    image: traefik:${PROXY_VERSION?latest}
    container_name: traefik
    ports:
      - ${PROXY_PORT?80}:80
      - ${PROXY_SECURE_PORT?443}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/acme.json:/acme.json
      - ./conf/traefik.yml:/traefik.yml
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`${PROXY_HOST}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.entrypoints=websecure'
      - 'traefik.http.routers.api.middlewares=auth'
      - "traefik.http.routers.api.tls=true"
      - 'traefik.http.middlewares.auth.basicauth.users=${PROXY_BASIC_AUTH}'
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.api-https.redirectscheme.scheme=https"
    networks:
      - traefik-public

  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION?latest}
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-public
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_PROXY_HOST}`)"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=${PORTAINER_LOADBALANCER_PORT?9000}"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.portainer-https.redirectscheme.scheme=https"

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: ${NETDATA_HOST}:${NETDATA_PORT}
    ports:
      - ${NETDATA_PORT}:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro

networks:
  traefik-public:
    external: true

volumes:
  netdataconfig:
  netdatalib:
  netdatacache: